### ISSUE TITLE
Maven build fails for plugin on develop, plugin/3.4, plugin/3.3 and master

### ISSUE THREAD

**Issue by philmaweb** [GeneMANIA/genemania#123]
Please include the command 
```
mvn install:install-file -Dfile=<path to repo>/genemania/engine/lib/mtj-0.9.14d.jar -DgroupId=com.googlecode.matrix-toolkits-java -DartifactId=mtj -Dversion=0.9.14d
```
In the Readme. Otherwise it's impossible to build the project as the jar is no longer in the repository.

Then the build completed for:
```
[INFO] Reactor Summary:
[INFO] 
[INFO] GeneMANIA Parent ................................... SUCCESS [  0.213 s]
[INFO] GeneMANIA Common ................................... SUCCESS [  2.120 s]
[INFO] GeneMANIA Engine ................................... SUCCESS [ 37.034 s]
[INFO] GeneMANIA Broker ................................... SUCCESS [  4.948 s]
[INFO] GeneMANIA Website .................................. SUCCESS [  9.926 s]
```

But plugin is missing.

running

```
mvn package -X -pl plugin -am
```
on the develop branch produced following output:

```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_191, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: nds_DE, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-36-generic", arch: "amd64", family: "unix"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/philipp/.m2/settings.xml
[DEBUG] Reading global toolchains from /usr/share/maven/conf/toolchains.xml
[DEBUG] Reading user toolchains from /home/philipp/.m2/toolchains.xml
[DEBUG] Using local repository at /home/philipp/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/philipp/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project org.genemania:parent:pom:3.6.0: (none)
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[plexus.core, parent: null]
[DEBUG] Extension realms for project org.genemania:genemania-common:jar:3.6.0: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[DEBUG] Extension realms for project org.genemania:genemania-engine:jar:3.6.0: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[DEBUG] Extension realms for project org.genemania:genemania-broker:jar:3.6.0: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[DEBUG] Extension realms for project org.genemania:genemania-website:war:3.6.0: (none)
[DEBUG] Looking up lifecyle mappings for packaging war from ClassRealm[plexus.core, parent: null]
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.genemania:genemania-broker:jar:3.6.0
[WARNING] 'build.plugins.plugin.version' for com.mycila.maven-license-plugin:maven-license-plugin is missing. @ org.genemania:genemania-broker:[unknown-version], /home/philipp/dev/genemania/broker/pom.xml, line 87, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ org.genemania:genemania-broker:[unknown-version], /home/philipp/dev/genemania/broker/pom.xml, line 62, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.genemania:genemania-website:war:3.6.0
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springframework:spring-context-support:jar -> duplicate declaration of version ${spring.version} @ org.genemania:genemania-website:[unknown-version], /home/philipp/dev/genemania/website/pom.xml, line 126, column 15
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:tomcat-maven-plugin is missing. @ org.genemania:genemania-website:[unknown-version], /home/philipp/dev/genemania/website/pom.xml, line 287, column 12
[WARNING] 'build.plugins.plugin.version' for com.mycila.maven-license-plugin:maven-license-plugin is missing. @ org.genemania:genemania-website:[unknown-version], /home/philipp/dev/genemania/website/pom.xml, line 353, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ org.genemania:genemania-website:[unknown-version], /home/philipp/dev/genemania/website/pom.xml, line 254, column 12
[WARNING] 'build.plugins.plugin.version' for org.codehaus.cargo:cargo-maven2-plugin is missing. @ org.genemania:genemania-website:[unknown-version], /home/philipp/dev/genemania/website/pom.xml, line 294, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.genemania:parent:pom:3.6.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 38, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[ERROR] [ERROR] Could not find the selected project in the reactor: plugin @ 
[ERROR] Could not find the selected project in the reactor: plugin -> [Help 1]
org.apache.maven.MavenExecutionException: Could not find the selected project in the reactor: plugin
	at org.apache.maven.graph.DefaultGraphBuilder.trimSelectedProjects(DefaultGraphBuilder.java:182)
	at org.apache.maven.graph.DefaultGraphBuilder.dependencyGraph(DefaultGraphBuilder.java:115)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:92)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

Switching to the branch "plugin/3.4"  using `git checkout plugin/3.4`.

A non-listed requirement here was subversion.

Running  `mvn package` also leads to 
```
[...]
[INFO] GeneMANIA Parent ................................... SUCCESS [  0.120 s]
[INFO] GeneMANIA Common ................................... SUCCESS [  2.935 s]
[INFO] GeneMANIA Engine ................................... SUCCESS [ 35.356 s]
[INFO] GeneMANIA Broker ................................... SUCCESS [  4.925 s]
[INFO] GeneMANIA Website .................................. SUCCESS [ 14.217 s]
[INFO] GeneMANIA Cytoscape App Parent ..................... SUCCESS [  0.376 s]
[INFO] org.genemania:plugin-core .......................... FAILURE [  0.032 s]
[INFO] org.genemania:plugin-cy2-support ................... SKIPPED
[INFO] org.genemania:plugin-cy26-support .................. SKIPPED
[INFO] org.genemania:plugin-cy2 ........................... SKIPPED
[INFO] org.genemania:plugin-distribution .................. SKIPPED
[INFO] GeneMANIA Cytoscape App ............................ SKIPPED
[INFO] GeneMANIA Admin Interface .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 58.854 s
[INFO] Finished at: 2018-10-19T19:36:06-04:00
[INFO] Final Memory: 93M/1734M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project plugin-core: Could not resolve dependencies for project org.genemania:plugin-core:jar:3.4.0: The following artifacts could not be resolved: zip64file:zip64file:jar:20091028, uispec4j:uispec4j:jar:2.0: Failure to find zip64file:zip64file:jar:20091028 in http://genemania.org/mvn/ was cached in the local repository, resolution will not be reattempted until the update interval of genemania_maven_repo has elapsed or updates are forced -> [Help 1]
```
`uispec4j:uispec4j:jar:2.0` predates 2009 and is no longer available at https://mvnrepository.com/artifact/org.uispec4j/uispec4j - similarly with `zip64file:zip64file:jar:20091028` - shouldn't there be an up to date pom for the 3.5 release?

**Comment by philmaweb** [comment]
maybe related to #98?

**Comment by maxkfranz** [comment]
From the readme: 

> You must clean the engine before building (at least once to install mtj): mvn clean

**Comment by philmaweb** [comment]
Thanks for your feedback. To clarify -  I want to build the Cytoscape `plugin/app` - not the website. 

As before the "complete" build on the `develop` branch completes successfully. But the `plugin` module/package is missing. When enabling the  `<module>plugin</module>` (line 18 in https://github.com/GeneMANIA/genemania/blob/develop/pom.xml ) the build fails.

I see it was disabled in commit 17d368de66cef21c9f37ff2045f732aeec55f886  - as it is possible to 

> built separately (and outside of jenkins) 

## So what I'm looking for is a branch from which I can build the plugin v3.5 or any other version after 3.2.


## Branch plugin/3.4
I checkout the `plugin/3.4` branch - clean the maven engine, and build the package:

```
git checkout plugin/3.4
mvn clean
mvn package
```

```
[...]
[INFO] ------------------------------------------------------------------------
[INFO] Building org.genemania:plugin-core 3.4.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for zip64file:zip64file:jar:20091028 is missing, no dependency information available
[WARNING] The POM for uispec4j:uispec4j:jar:2.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] GeneMANIA Parent ................................... SUCCESS [  0.159 s]
[INFO] GeneMANIA Common ................................... SUCCESS [  4.739 s]
[INFO] GeneMANIA Engine ................................... SUCCESS [ 39.920 s]
[INFO] GeneMANIA Broker ................................... SUCCESS [  5.314 s]
[INFO] GeneMANIA Website .................................. SUCCESS [ 14.042 s]
[INFO] GeneMANIA Cytoscape App Parent ..................... SUCCESS [  0.301 s]
[INFO] org.genemania:plugin-core .......................... FAILURE [  0.030 s]
[INFO] org.genemania:plugin-cy2-support ................... SKIPPED
[INFO] org.genemania:plugin-cy26-support .................. SKIPPED
[INFO] org.genemania:plugin-cy2 ........................... SKIPPED
[INFO] org.genemania:plugin-distribution .................. SKIPPED
[INFO] GeneMANIA Cytoscape App ............................ SKIPPED
[INFO] GeneMANIA Admin Interface .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

## Branch plugin/3.3

```
git checkout plugin/3.3
cd plugin
mvn clean
mvn package
```

```
[...]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.genemania:plugin-parent ........................ SUCCESS [  0.533 s]
[INFO] org.genemania:plugin-core .......................... FAILURE [  6.354 s]
[INFO] org.genemania:plugin-cy2-support ................... SKIPPED
[INFO] org.genemania:plugin-cy26-support .................. SKIPPED
[INFO] org.genemania:plugin-cy2 ........................... SKIPPED
[INFO] org.genemania:plugin-distribution .................. SKIPPED
[INFO] GeneMANIA .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.488 s
[INFO] Finished at: 2018-10-22T15:02:37-04:00
[INFO] Final Memory: 18M/362M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project plugin-core: Could not resolve dependencies for project org.genemania:plugin-core:jar:3.3.4: The following artifacts could not be resolved: zip64file:zip64file:jar:20091028, uispec4j:uispec4j:jar:2.0, org.genemania:genemania-common:jar:3.1.2, org.genemania:genemania-engine:jar:3.1.3: Failure to find zip64file:zip64file:jar:20091028 in http://genemania.org/mvn/ was cached in the local repository, resolution will not be reattempted until the update interval of genemania_maven_repo has elapsed or updates are forced -> [Help 1]
```


## Branch master

```
git checkout master
cd plugin
mvn clean
mvn package
```

```
[...]
[INFO] Reactor Summary:
[INFO] 
[INFO] org.genemania:plugin-parent ........................ SUCCESS [  0.514 s]
[INFO] org.genemania:plugin-core .......................... FAILURE [  5.220 s]
[INFO] org.genemania:plugin-cy2-support ................... SKIPPED
[INFO] org.genemania:plugin-cy26-support .................. SKIPPED
[INFO] org.genemania:plugin-cy2 ........................... SKIPPED
[INFO] org.genemania:plugin-distribution .................. SKIPPED
[INFO] GeneMANIA .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.333 s
[INFO] Finished at: 2018-10-22T15:08:59-04:00
[INFO] Final Memory: 18M/364M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project plugin-core: Could not resolve dependencies for project org.genemania:plugin-core:jar:3.2: The following artifacts could not be resolved: zip64file:zip64file:jar:20091028, uispec4j:uispec4j:jar:2.0, org.genemania:genemania-common:jar:3.1.1, org.genemania:genemania-engine:jar:3.1.1: Failure to find zip64file:zip64file:jar:20091028 in http://genemania.org/mvn/ was cached in the local repository, resolution will not be reattempted until the update interval of genemania_maven_repo has elapsed or updates are forced -> [Help 1]
```

In both plugin branches and the `master` branch (for version 3.2 of the plugin) `zip64file:zip64file:jar:20091028` and  `uispec4j:uispec4j:jar:2.0` are missing - which results in a Build Failure. 

Your help would be greatly appreciated.

**Comment by philmaweb** [comment]
@chrtannus talking about this issue

**Comment by philmaweb** [comment]
Working build procedure:
```
cd genemania
mvn clean
mvn clean install -am -P prod -U
cd plugin
mvn clean install -am -P prod -U
cd plugin-cy3
mvn clean install -am -P prod -U
```

The resulting jar can be found in

`genemania/plugin/plugin-cy3/target/plugin-cy3-3.5.0.jar`
